### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by houxiaolinzhengdan** [SlicerDMRI/SupWMA#2]
Dear Zhang, I am Hou Xiaolin, a neurosurgeon from the Affiliated Hospital of Chengdu University of Traditional Chinese Medicine. I was lucky to see your Supwma study. I used your Git code. According to the instructions, there will be mistakes, I would like to ask you how to solve this problem, thank you. Is this a problem with the 3dslicer version?

**Comment by tengfeixue-victor** [comment]
This issue seems to be repeated. I will close this one. Thanks
