### ISSUE TITLE
Help on how to train on custom public dataset!

### ISSUE THREAD

**Issue by anoushkrit** [SlicerDMRI/SupWMA#5]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/23333901/172679154-4ae9f68f-2529-40e7-a300-b135dd64865d.png">

This is a snapshot of a subject from dHCP dataset, and I want to try out the SupWMA code on the same. I am finding difficulty in understanding how the data is passed through as a custom TrainDataset, from what I have gathered as of now is that I require a `.nrrd` and a `.vtp` file for starting the training process. But I have `.bvec`, `.bval` , brain data `.nii.gz` and the mask `.nii.gz`, how can I go forward with this, I have found some of the slicer implementations for conversion of data types, but I think that won't be enough. Also I think there is a requirement of `sf_clusters_train_featMatrix.h5` like file for training the model. 
@tengfeixue-victor Can you please help me with the same and also provide the preprocessing script used by you? 

PS: I am new to the neuroimaging field and would like increase my knowledge in the same.

**Comment by zhangfanmark** [comment]
Hi @anoushkrit 

We used DWIConvert to convert the data from nifti format to nrrd format. The Nrrd format is what being used in SlicerDMRI to run tractography. You can used the following code to do the conversion: https://github.com/pnlbwh/conversion

Regards,
Fan

**Comment by anoushkrit** [comment]
Thank you for the answer! The solution worked for us.
We are currently trying to train the model on a public dataset which was mentioned in the paper DeepWMA, i.e dHCP dataset. So the issue we are facing is the error of `No zero gradients`, even after converting both input_dwi and mask to `nrrd` using `nhdr_write.py`. Please tell me what am I doing wrong here.
I have specified --dwiFile, --labels 1, --maskFile, --numTensor 2, and the output tract path, is there anything else I need to add in this? The source of the data remains the same as above in the image (having bval, bvec, mask, dwi)

![image](https://user-images.githubusercontent.com/23333901/192607274-97eb912c-9ffc-486b-b2aa-4726a1f2b202.png)
